# Populate test data for Tasks, Notes, and Journals (40 of each type)

Write-Host "Creating 40 test Tasks..." -ForegroundColor Cyan

# Tasks with various tags and due dates
cargo run -- add-task "Review quarterly reports" --due "2024-12-31" --tags "work,urgent"
cargo run -- add-task "Buy groceries" --due "2024-12-20" --tags "personal,shopping"
cargo run -- add-task "Finish project documentation" --due "2024-12-25" --tags "work,documentation"
cargo run -- add-task "Call dentist" --tags "personal,health"
cargo run -- add-task "Update resume" --due "2025-01-15" --tags "work,career"
cargo run -- add-task "Plan vacation" --tags "personal,travel"
cargo run -- add-task "Fix bug in login system" --due "2024-12-18" --tags "work,urgent,development"
cargo run -- add-task "Read new book chapter" --tags "personal,learning"
cargo run -- add-task "Team meeting preparation" --due "2024-12-19" --tags "work,meeting"
cargo run -- add-task "Exercise routine" --tags "personal,health,fitness"
cargo run -- add-task "Write unit tests for API" --due "2024-12-22" --tags "work,development,testing"
cargo run -- add-task "Schedule doctor appointment" --tags "personal,health"
cargo run -- add-task "Review pull requests" --due "2024-12-17" --tags "work,code-review"
cargo run -- add-task "Organize home office" --tags "personal,organization"
cargo run -- add-task "Prepare presentation slides" --due "2024-12-23" --tags "work,presentation"
cargo run -- add-task "Learn new programming language" --tags "personal,learning,programming"
cargo run -- add-task "Update dependencies" --due "2024-12-21" --tags "work,maintenance"
cargo run -- add-task "Plan birthday party" --tags "personal,event"
cargo run -- add-task "Refactor legacy code" --due "2025-01-10" --tags "work,development,refactoring"
cargo run -- add-task "Meditation session" --tags "personal,wellness"
cargo run -- add-task "Deploy to staging" --due "2024-12-24" --tags "work,deployment"
cargo run -- add-task "Research vacation destinations" --tags "personal,travel,research"
cargo run -- add-task "Write blog post" --due "2025-01-05" --tags "work,writing"
cargo run -- add-task "Clean garage" --tags "personal,chores"
cargo run -- add-task "Optimize database queries" --due "2024-12-26" --tags "work,performance,database"
cargo run -- add-task "Try new restaurant" --tags "personal,food"
cargo run -- add-task "Set up CI/CD pipeline" --due "2025-01-08" --tags "work,devops"
cargo run -- add-task "Practice guitar" --tags "personal,hobby,music"
cargo run -- add-task "Review security audit" --due "2024-12-27" --tags "work,security"
cargo run -- add-task "Organize photos" --tags "personal,organization"
cargo run -- add-task "Implement new feature" --due "2025-01-12" --tags "work,development,feature"
cargo run -- add-task "Visit family" --tags "personal,family"
cargo run -- add-task "Update documentation" --due "2024-12-28" --tags "work,documentation"
cargo run -- add-task "Start new book" --tags "personal,reading"
cargo run -- add-task "Fix production bug" --due "2024-12-16" --tags "work,urgent,bugfix"
cargo run -- add-task "Plan weekend activities" --tags "personal,weekend"
cargo run -- add-task "Code review session" --due "2024-12-29" --tags "work,code-review"
cargo run -- add-task "Learn cooking recipe" --tags "personal,food,cooking"
cargo run -- add-task "Set up monitoring" --due "2025-01-20" --tags "work,devops,monitoring"
cargo run -- add-task "Declutter workspace" --tags "personal,organization"
cargo run -- add-task "Write technical spec" --due "2025-01-18" --tags "work,documentation,planning"

Write-Host "`nCreating 40 test Notes..." -ForegroundColor Cyan

# Notes with various content and tags
cargo run -- add-note "Meeting Notes - December" --content "Discussed Q4 goals and planning for next year. Key points: budget approval, team expansion, new project timeline." --tags "work,meeting,notes"
cargo run -- add-note "Recipe Ideas" --content "Chocolate chip cookies, pasta carbonara, chicken curry. Need to try the new Italian restaurant." --tags "personal,food"
cargo run -- add-note "Book Recommendations" --content "The Pragmatic Programmer, Clean Code, Design Patterns. Also check out 'The Art of Computer Programming'." --tags "learning,books"
cargo run -- add-note "Project Ideas" --content "Build a personal finance tracker, create a recipe app, start a blog about Rust programming." --tags "personal,projects"
cargo run -- add-note "Shopping List" --content "Milk, eggs, bread, cheese, tomatoes, onions, chicken breast, pasta, olive oil" --tags "personal,shopping"
cargo run -- add-note "Code Snippets" --content "Useful Rust patterns: Option.map(), Result.and_then(), iterator chains. Remember to use clippy!" --tags "work,development,rust"
cargo run -- add-note "Travel Plans" --content "Visit Japan in spring, explore Kyoto temples, try authentic ramen, see cherry blossoms." --tags "personal,travel"
cargo run -- add-note "Daily Reflection" --content "Today was productive. Completed the authentication module and started on the dashboard. Need to focus on testing tomorrow." --tags "personal,reflection"
cargo run -- add-note "Quick Reference" --content "Git commands: git status, git add ., git commit -m, git push. Docker: docker build, docker run, docker ps" --tags "work,reference"
cargo run -- add-note "Ideas for Weekend" --content "Hike in the mountains, visit the art museum, try that new coffee shop, finish reading current book." --tags "personal,weekend"
cargo run -- add-note "API Endpoints" --content "/api/users, /api/tasks, /api/notes. Authentication required for all endpoints. Use JWT tokens." --tags "work,development,api"
cargo run -- add-note "Movie Watchlist" --content "The Matrix, Inception, Interstellar, Blade Runner 2049, Dune. Need to catch up on sci-fi classics." --tags "personal,entertainment"
cargo run -- add-note "Database Schema Notes" --content "Users table: id, email, password_hash. Tasks table: id, user_id, title, status. Foreign keys properly indexed." --tags "work,database,design"
cargo run -- add-note "Gift Ideas" --content "Books, coffee, art supplies, tech gadgets, experience vouchers. Keep it thoughtful and personal." --tags "personal,gifts"
cargo run -- add-note "Error Handling Patterns" --content "Use Result types, implement proper error propagation, log errors appropriately, provide user-friendly messages." --tags "work,development,patterns"
cargo run -- add-note "Restaurant Reviews" --content "The Italian place downtown: 5/5 stars. Great pasta and atmosphere. The sushi bar: 4/5, fresh but expensive." --tags "personal,food,reviews"
cargo run -- add-note "Performance Optimization" --content "Cache frequently accessed data, use database indexes, implement pagination, optimize queries, use CDN for static assets." --tags "work,performance,optimization"
cargo run -- add-note "Weekend Trip Ideas" --content "Mountain hiking, beach visit, city exploration, wine tasting tour, camping adventure. Need to decide soon." --tags "personal,travel,weekend"
cargo run -- add-note "Testing Strategies" --content "Unit tests for functions, integration tests for APIs, E2E tests for critical flows. Aim for 80% coverage." --tags "work,testing,quality"
cargo run -- add-note "Home Improvement Ideas" --content "Paint living room, organize garage, install new shelves, upgrade lighting, add plants for better air quality." --tags "personal,home"
cargo run -- add-note "Security Best Practices" --content "Use HTTPS, hash passwords, validate input, sanitize output, implement rate limiting, regular security audits." --tags "work,security"
cargo run -- add-note "Learning Resources" --content "Rust Book, MDN Web Docs, Stack Overflow, GitHub repos, YouTube tutorials, online courses." --tags "learning,resources"
cargo run -- add-note "Deployment Checklist" --content "Run tests, check environment variables, backup database, update documentation, notify team, monitor logs." --tags "work,deployment,checklist"
cargo run -- add-note "Fitness Goals" --content "Run 3 times per week, strength training twice, yoga on weekends, track progress, stay consistent." --tags "personal,health,fitness"
cargo run -- add-note "Code Review Guidelines" --content "Check logic, test edge cases, verify error handling, ensure code style, check performance, verify security." --tags "work,code-review,guidelines"
cargo run -- add-note "Recipe Collection" --content "Pasta aglio e olio, chicken stir-fry, chocolate cake, homemade pizza, vegetable curry. All tested and delicious." --tags "personal,food,recipes"
cargo run -- add-note "Architecture Decisions" --content "Microservices for scalability, REST API for simplicity, PostgreSQL for reliability, Redis for caching." --tags "work,architecture,decisions"
cargo run -- add-note "Book Quotes" --content "'The only way to do great work is to love what you do.' - Steve Jobs. 'Code is like humor. When you have to explain it, it's bad.'" --tags "personal,inspiration,quotes"
cargo run -- add-note "Monitoring Setup" --content "Set up error tracking, performance monitoring, uptime checks, log aggregation, alerting rules." --tags "work,monitoring,devops"
cargo run -- add-note "Hobby Projects" --content "Build a weather app, create a personal blog, develop a game, contribute to open source, learn photography." --tags "personal,projects,hobbies"
cargo run -- add-note "Team Communication" --content "Daily standups, weekly retrospectives, async updates in Slack, document decisions, share knowledge." --tags "work,communication,team"
cargo run -- add-note "Travel Checklist" --content "Passport, tickets, hotel booking, travel insurance, currency exchange, local SIM card, emergency contacts." --tags "personal,travel,checklist"
cargo run -- add-note "Refactoring Notes" --content "Extract common functions, reduce duplication, improve naming, simplify logic, add comments where needed." --tags "work,refactoring,code-quality"
cargo run -- add-note "Productivity Tips" --content "Pomodoro technique, time blocking, eliminate distractions, batch similar tasks, take regular breaks." --tags "personal,productivity"
cargo run -- add-note "API Documentation" --content "Document endpoints, request/response formats, error codes, authentication, rate limits, examples." --tags "work,documentation,api"
cargo run -- add-note "Investment Ideas" --content "Research index funds, consider real estate, look into stocks, emergency fund first, diversify portfolio." --tags "personal,finance,investment"
cargo run -- add-note "Debugging Techniques" --content "Use debugger, add logging, check logs, reproduce issue, isolate problem, test hypotheses, fix root cause." --tags "work,debugging,development"
cargo run -- add-note "Health Tips" --content "Drink water, get sleep, exercise regularly, eat vegetables, reduce stress, take breaks, stay active." --tags "personal,health,wellness"
cargo run -- add-note "Design Patterns" --content "Singleton, Factory, Observer, Strategy, Decorator, Adapter. Know when to use each pattern appropriately." --tags "work,development,patterns"
cargo run -- add-note "Event Planning" --content "Choose venue, set date, send invitations, plan menu, organize activities, prepare backup plan." --tags "personal,events,planning"
cargo run -- add-note "Version Control Workflow" --content "Create feature branch, make commits, push regularly, create PR, address feedback, merge after approval." --tags "work,git,workflow"

Write-Host "`nCreating 40 test Journal entries..." -ForegroundColor Cyan

# Journal entries with various dates, titles, and tags
cargo run -- add-journal "Had a great day at work today. Completed the authentication system and got positive feedback from the team. Feeling motivated!" --title "Productive Day" --tags "work,reflection"
cargo run -- add-journal "Went for a long walk in the park. The weather was perfect and it helped clear my mind. Planning to make this a regular habit." --title "Nature Walk" --tags "personal,health"
cargo run -- add-journal "Started learning Rust today. The ownership system is challenging but interesting. Working through the Rust Book exercises." --title "Learning Rust" --tags "learning,rust"
cargo run -- add-journal "Team meeting went well. Discussed the new project timeline and everyone seems excited. Assigned tasks for next sprint." --title "Team Meeting" --tags "work,meeting"
cargo run -- add-journal "Cooked a delicious pasta dinner tonight. Tried a new recipe and it turned out great. Need to remember to buy more parmesan cheese." --title "Cooking Adventure" --tags "personal,food"
cargo run -- add-journal "Feeling a bit overwhelmed with tasks. Need to prioritize better and maybe use the Pomodoro technique. Taking a break now." --title "Time Management" --tags "personal,reflection"
cargo run -- add-journal "Fixed three bugs today and wrote comprehensive tests. Code review went smoothly. Feeling accomplished!" --title "Bug Fixing Day" --tags "work,development"
cargo run -- add-journal "Read an interesting article about productivity. Key takeaway: focus on one task at a time and eliminate distractions." --title "Productivity Tips" --tags "learning,productivity"
cargo run -- add-journal "Went to the gym for the first time in weeks. It felt good to get back into the routine. Planning to go three times this week." --title "Back to Fitness" --tags "personal,health,fitness"
cargo run -- add-journal "Spent the evening working on a side project. Made good progress on the UI components. Excited to see it come together!" --title "Side Project Progress" --tags "personal,projects"
cargo run -- add-journal "Deployed the new feature to production today. Everything went smoothly with zero downtime. The team did a great job!" --title "Successful Deployment" --tags "work,deployment"
cargo run -- add-journal "Tried a new coffee shop downtown. The atmosphere was cozy and the coffee was excellent. Will definitely return." --title "Coffee Shop Discovery" --tags "personal,food,exploration"
cargo run -- add-journal "Attended a tech conference virtually. Learned about new frameworks and best practices. Feeling inspired to try new things." --title "Tech Conference" --tags "learning,conference"
cargo run -- add-journal "Had a difficult debugging session today. Spent hours tracking down a subtle bug, but finally found it. Persistence pays off!" --title "Debugging Marathon" --tags "work,debugging"
cargo run -- add-journal "Spent quality time with family today. We played board games and had great conversations. These moments are precious." --title "Family Time" --tags "personal,family"
cargo run -- add-journal "Completed a code review and provided constructive feedback. Helped a teammate improve their code quality. Collaboration is key." --title "Code Review Session" --tags "work,code-review"
cargo run -- add-journal "Went hiking in the mountains. The view from the top was breathtaking. Nature always helps me recharge." --title "Mountain Hike" --tags "personal,outdoors,nature"
cargo run -- add-journal "Implemented a new caching layer that improved performance significantly. The metrics show a 40% improvement in response time." --title "Performance Win" --tags "work,performance,optimization"
cargo run -- add-journal "Started reading a new book about software architecture. Already learning valuable concepts that I can apply to my work." --title "Reading Session" --tags "personal,learning,reading"
cargo run -- add-journal "Had a productive brainstorming session with the team. Came up with several innovative solutions to our current challenges." --title "Brainstorming" --tags "work,planning,innovation"
cargo run -- add-journal "Tried meditation for the first time in a while. It was challenging to quiet my mind, but I felt more relaxed afterward." --title "Meditation Practice" --tags "personal,wellness,mindfulness"
cargo run -- add-journal "Refactored a large module today. The code is now much cleaner and easier to maintain. Technical debt reduction feels good." --title "Refactoring Success" --tags "work,refactoring,code-quality"
cargo run -- add-journal "Visited an art museum with friends. The contemporary art section was particularly inspiring. Art feeds the soul." --title "Museum Visit" --tags "personal,culture,art"
cargo run -- add-journal "Set up monitoring and alerting for our production system. Now we'll catch issues before they become problems." --title "Monitoring Setup" --tags "work,devops,monitoring"
cargo run -- add-journal "Cooked a three-course meal for friends. Everyone enjoyed it and asked for recipes. Cooking is becoming a real passion." --title "Dinner Party" --tags "personal,food,cooking"
cargo run -- add-journal "Wrote comprehensive documentation for the new API. Good documentation is crucial for team productivity and onboarding." --title "Documentation Work" --tags "work,documentation"
cargo run -- add-journal "Went to a concert tonight. The live music was incredible and the energy was amazing. Music is such a powerful experience." --title "Concert Experience" --tags "personal,entertainment,music"
cargo run -- add-journal "Fixed a critical security vulnerability that was discovered in our codebase. Security is always a top priority." --title "Security Fix" --tags "work,security"
cargo run -- add-journal "Spent the day organizing my workspace. A clean and organized environment really helps with productivity and focus." --title "Workspace Organization" --tags "personal,organization"
cargo run -- add-journal "Participated in a hackathon over the weekend. Built a fun project with teammates and learned new technologies." --title "Hackathon Weekend" --tags "work,learning,hackathon"
cargo run -- add-journal "Took a photography walk around the city. Captured some interesting shots of architecture and street scenes." --title "Photography Walk" --tags "personal,hobby,photography"
cargo run -- add-journal "Optimized database queries that were causing performance issues. The application now runs much faster." --title "Database Optimization" --tags "work,database,performance"
cargo run -- add-journal "Had a deep conversation with a friend about life goals and aspirations. These meaningful conversations are so valuable." --title "Deep Conversation" --tags "personal,reflection,friendship"
cargo run -- add-journal "Implemented a new feature that users have been requesting. Looking forward to seeing their feedback and usage." --title "Feature Release" --tags "work,development,feature"
cargo run -- add-journal "Went stargazing on a clear night. The sky was beautiful and it reminded me how vast the universe is." --title "Stargazing Night" --tags "personal,nature,reflection"
cargo run -- add-journal "Conducted a training session for new team members. Teaching others helps reinforce my own understanding." --title "Team Training" --tags "work,teaching,team"
cargo run -- add-journal "Started a new fitness routine. First session was tough but I'm committed to sticking with it this time." --title "Fitness Journey" --tags "personal,health,fitness"
cargo run -- add-journal "Reviewed and improved our error handling across the application. Better error messages will improve user experience." --title "Error Handling Improvements" --tags "work,development,quality"
cargo run -- add-journal "Spent the afternoon at a local farmers market. Bought fresh produce and enjoyed the community atmosphere." --title "Farmers Market" --tags "personal,food,community"
cargo run -- add-journal "Completed a major milestone in our project. The team celebrated together. Hard work and collaboration made it possible." --title "Milestone Celebration" --tags "work,team,celebration"
cargo run -- add-journal "Tried a new hobby - pottery. It's harder than it looks but very meditative. Looking forward to improving." --title "Pottery Class" --tags "personal,hobby,learning"
cargo run -- add-journal "Wrote unit tests for a complex module. Achieved 90% code coverage. Testing gives me confidence in the code." --title "Testing Achievement" --tags "work,testing,quality"
cargo run -- add-journal "Had a relaxing day reading and listening to music. Sometimes you need these quiet days to recharge." --title "Quiet Day" --tags "personal,relaxation,wellness"
cargo run -- add-journal "Architected a new system design for an upcoming feature. Planning ahead will save time in implementation." --title "System Design" --tags "work,architecture,planning"

Write-Host "`nTest data population complete! Created 40 Tasks, 40 Notes, and 40 Journal entries." -ForegroundColor Green
